* About
  Hello, I am Mohamed Fouad a.k.a zotherstupidguy, a Software
  Philosopher living in Alexandria, Egypt; and this is my day-to-day b(log). 
  I am available for [hire [link to google docs resume]].
  This is an org-mode generated log (Org-Agenda, Org-Capture, tag-based organization) via those [[https://github.com/zotherstupidguy/dotfiles][dotfiles]] 
  and acutal [[https://github.com/zotherstupidguy/zotherstupidguy.github.io][source]] of this blog. 
  
  -----

  Why zotherstupidguy nick? it is a joke and a reminder that being smart is totally relevant to my current knowledge circles,
  and I must always seek ideas outside of my regular knowledge circles, anything that I am already familair with probably wouldn't breed me 
  an *orginal* idea, I must seek doctrine depth through skeptic breadths!

  -----
  
  *As lazy as I am*, I plan using the notes here *to cheat at phone interviews*, 
  Emacs got a nice regex search ;) IF YOU BELONG TO THE SET OF THE FEW PEOPLE 
  ON EARTH WHO READ MY BLOG *AND* ACTUALLY PLAN TO HIRE ME, 
  PLEASE LET ME KNOW IF YOU THINK I AM FUNNY.

  -----
  Once in a while, I examine how Top Universities offer their mathematics and computer science related programs. I try to find what kind of books they set as 
  textbooks, to go read them on my own, purchase them from Amazon (I only like *Hardcover* books!), or scout them in the cheap 2nd hand street book markets. 
  My act is inspired by *“You wasted $150,000 on an education you coulda got for $1.50 in late fees at the public library.” ― Matt Damon, Good Will Hunting*. 
  I worship those Professors who offer their courses online for free! If it is up to me I build them real-size human sculptures in my City. 
  *Knoweldge belong to all mankind, not to copyright owners who suffer from financial insecurities!*
  ----- 
  Public keys(if you wish to communicate with me securely)
  ----- 
  Strategy is doing the right things, tactics is doing things right! 

** Funny Thoughts

   Anicent Egyptians had n gods, as each person was ws focused into their profession that they created a god for thisf sf sf sf sf sf sf sf sf sf sf sf sf sf sf sf sf sf

   Anicent Egyptians had n gods, as each person was so focused into their profession that they created a god for this body of knowledge to worship day and night. if computer

   Anicent Egyptians had n gods, as each person was so focused into their
   profession that they created a god for this body of knowledge to
   worship day and night. If computer science folks would do the same,
   they would create Knuth God, after Donald Knuth :D    

** Companies I would like to work for
   - Thoughtbot
   - Github
   - Google
   - Amazon
   - Thoughtworks
   - Gitlab
   - Facebook
   - Twitter
   - Hackerrank
   ----- 
** Why should we hire you?
   Because AI is not that good "yet", and you and I still need other humans to survive!
** Grit :: Perseverance and Passion for Long-term Goals 
   :PROPERTIES:
   :DESCRIPTION: Must have Personal Traits via continous conditioning
   :CATEGORY: research
   :ZPT:      0
   :END:
   + Courage
     - understand that there are valuable lessons in defeat and that the vulnerability of perseverance is requisite for high achievement.  
     - 
     - 
   -----

** Studying Strategy 
   My study strategy says that each book, videocourse, etc. is in one direcotry. This is my study log, I keep all the 
   knowledge that I aquire into this file, and I organize it accordingly to smallest possible domain of knowledge such as instead of having
   a heading for Number Theory, I have multiple headings for topics such as Prime Numbers, that way when I read a book I don't read the chapters but
   I explore the glossry and find where my objective topic exists and I write it down based on:  
   - why is it worth the effort?
   - what should be persued? 
   - how it will be persued?

*** Cornell Note Taking System & Feynman Technique
    I employ the Feynman technique in the Reviewing stage of my SQ3R 

    Refs: 
    - Learn Faster with The Feynman Technique
    https://www.youtube.com/watch?v=FrNqSLPaZLc

    - How to Learn Faster with the Feynman Technique:  
    https://www.youtube.com/watch?v=_f-qkGJBPts


*** Finding Sources
    using ./link to automatically download new youtube videos and generate an RSS of it and update log.org with a TODO for watching new things.
    I can't add ZPT, can, and can't folders in the sources folders as it will make ./link difficult to know what already got downloaded.


    ----- 

** Training Strategy
   The main idea of Competitive Programming Training is to solve any given problem in under 10minutes, thus the 
   most basic studytime unit  is t = 10mins, henceforth all my study and practice activites are divided up in units of 10mins.

   I categorieze my incoming infromation into 3 categories: 
   A. Can,    12 problems, total 12t(2hrs)
   B. ZPD,    4 problems, total 12t(2hrs)
   C. Can't.  1 problem, total 12t(2hrs)

** ZotherZPD(Zone of Proximal Development) Index
   - Can't is *0  =  ZPD0, thus I name respective headings with :zpd0:
   - ZPD is *1    = ZPD1, thus I name respective headings with :zpd1;
   - Can is *2    = ZPD2, thus I name respective headings with :zpd2:
     According to this index I can *automatically* calculate (via emacs) 
   a score * 0 or * 1 or * 2 / by the number of shit I am trying to accomplish.


   I start my day trying to attack category *C. Can't* to fail and study a bit, 
   then go for the *B.ZPD* which is my zone of proximal development, 
   with some effort I can succeed in solving a problem in 30mins.
   then I end my day with the *A.can* somthing that I solved before or know I can solve. 
   Simple Objectives results in Simple Delights makes me happy at the end of the day. 

   After Studying or Practice, blog about it using the Feynman Technique,  

   All problems are solved in C with emacs templates to save time.

   In order to achieve that training is divided into 3 difficulity/time categories: ZPT0, ZPT1, ZPT2.
   - 2hrs for *one* ZPT0 problem, this is a problem that are too difficult to solve and requires significant studying  
   to be familiar with the nessesary knowledge domain(s), 
     the 2hours are dedicated for 
     - Understanding the problem
     - Identifying which knowledge domain(s) it belongs to.
     - Reading about those knowledge domain(s).
     - Attempt to provide a solution  
     - 2hrs for *up to 4* ZPT1 problems, those are problems that their solutions depends on knowledge domain(s) 
     that I am already familiar with. 
     - 2hrs for *up to 12* ZPT2 problems, those are probems that I solved in the past one time or more and 
     I need to enhance my speed in solving them.


   ----- 

** Publish it! 
   Naturally I could write a book or two from the notes I have written into this file. As a matter of fact, I belive that
   *the only way* computer scientets are capable of writing so many powerful books is due to the fact that they use
   emacs in a similar way to what I am doing here, I can collect information and tag it, search it easily and update it,
   check cross references, etc. *It feels Awesome to be that Powerful!* I think i will keep taking notes in notebooks and as a review, I 
   will transfer the notes to this org document. I expect to be able to have codeblocks, latex formulas and maybe even 
   graphs. Eventually I shall publish a series about computer science via https://leanpub.com, call it "zotherstupidguy computer science notes" 
   each volume is small 100pages book of notes and commentary. 

** Brain Waves
   Each of us can use brainwave entrainment to achieve a variety of results. 
   You may want to target a specific brainwave frequency range to help you relax,. 
   On the other hand you may want to increase you creative energy, improve your memory, 
   deepen your sleep or get better results when playing a sport.
*** Beta brainwaves
    (14 to 32 Hz alert, focused)
    Beta is the most common brain wave pattern: Beta brainwaves are produced when we are wide awake, alert, 
    active and engaged in mental activity, usually involving more the rational, reality-oriented left hemisphere of our brain. 
    When beta wave activity becomes very intense, our brain hemispheres become less synchronized. 
    Beta state is required to function properly in your everyday life.
**** Features and Benefits of a Beta State
     - This is the brainwave for the fight-flight response
     - Increased concentration and alertness
     - Improved logic, reasoning and critical thinking
     - Feelings of anxiety, stress, scatty unfocused thought
     NOTE: Excessive Beta brainwaves are also a feature of insomnia
 
*** Alpha brainwaves
    (7 to 14 Hz relaxed yet aware, meditative)
    These are lower frequency waves: The state is generated when our thoughts are really not concentrated and our minds wonder freely, 
    or we are in a relaxed state such as meditating or daydreaming. We also experience Alpha Brainwaves when we are gently busy i
    with routine tasks like pottering in the garden, taking a shower, putting on makeup, doing light housework. 
    Alpha is considered to be the bridge between the conscious mind and the subconscious mind.

**** Features and Benefits of an Alpha State
     - Our brain hemispheres become naturally synchronized, or in-phase with each other.
     - Relaxed detached (absent-minded) awareness and daydreaming mind.
     - Enables us to remember our dreams and meditative states.
     - Link between conscious and subconscious mind, gateway to meditation.
     - Receptive to casual and auto – suggestions (hypnosis state)
     - Increased vividness benefits creative visualization and triggers imagination
     - Increased  memory retention , concentration & focus for super learning
**** Health benefits include:
     - Reduced anxiety
     - Alleviates stress and depression
     - Reduces chronic pain
     - Reduction of high blood pressure
     - Increases athletic performance
     - Increased  cerebral blood flow
     - Increased motivation, energy, and happiness

*** Theta brainwaves
    (3.5 to 7 Hz deep relaxation, twilight state)
    Theta brainwave states have been used in meditation for centuries: It is common for people to feel as if they are in a trance, 
    where the mind feels as though it may have gone to sleep although it is conscious of what is happening around it. 
    Theta induces a capacity for prolonged daydreaming, where a loss of time may be experienced.
    Theta waves are also conducive to visualization and creativity and the mind in this very relaxed state is highly receptive to direct suggestion under hypnosis. As with Alpha, in Theta our brain hemispheres are synchronized and we experience whole brain functioning.

**** Features and benefits of Theta brainwaves
     - Increased sense of inner peace and emotional stability
     - Deep relaxation
     - Improved memory
     - Heightened intuition and inspiration
     - Calms the chatter of your mind
     - Increased psychic abilities and sense of spiritual connection
     - Health benefits of Theta brainwaves
     - Speed healing, improved physical healing
     - Sleep onset and better more restful sleep
     - Release beneficial hormones related to health and longevity
     - Reduce mental fatigue
     - Reduction of anxiety and stress
     NOTE: Research has proven thirty minutes a day of Theta meditation can dramatically improve a person’s overall health and well-being. Theta meditation has also been known to result in a reduced need for sleep.
 
*** Delta brainwaves
    (0.1 to 3.5 Hz deep sleep )
    This is the slowest band of waves that our brains produce and they occur when we are in deep, dreamless sleep. 
    These waves are very beneficial for the body which restores and heals itself when in this state. 
    The delta state releases anti-aging hormones, including melatonin and DHEA. 
    Human growth hormone (HGH) is another anti-aging hormone that is increased when delta brainwaves are occurring inside the brain, 
    due to the stimulation of the pituitary gland. HGH maintains the skin, bone density, cartilage, and the joints in your body as 
    well as speeds up the healing process of joint and cartilage injuries. HGH can also help heal physical pain.

    In healthy amounts, delta brainwaves can also cause a person to have an advanced state of empathy, understanding, and compassion for others.
    Delta is the place of deepest relaxation, deepest healing, deepest spiritual connection and deepest connection with the subconscious mind. 
    It is considered to be the gateway to the unconscious mind and the collective unconscious, bringing access to the universal psyche or mind.
 
*** Gamma brainwaves
    (40Hz or higher: zen mind mastery)
    Gamma brainwave states are the most rapid in frequency. 
    Gamma hase long been considered the the brainwave that is able to link and process information from all parts of the brain. 
    It is the frequency that brings with it the ability to process large amounts of information in relatively small amounts of time. 
    Think of generating more Gamma activity as getting a processor upgrade for your brain.

    Unfortunately Gamma brainwaves have received the least attention and research, although more attention is currently being paid to them.
    Having high amounts of Gamma Brainwave activity has been associated with:
    - Having high levels of intelligence
    - Being compassionate
    - Having high amounts of self-control
    - Having greater than average feelings of natural happiness.
    - Increased awareness through your five senses
    - Research has indicated at moments when bursts of precognition or high-level information processing occur, 
    your brainwaves briefly reach the Gamma state.

** IRC
   #emacs ##algorithms ##puzzles #gcj #hackerrank  
   if using weechat `/set irc.server.freenode.autojoin "##algorithms #emacs #gcj"`
   but usually use emacs's irc erc

** The Role of a Teacher (supervised learning)
   The purpose of a teacher is to raise the *right* questions for the student. 
   The role of a student is to seek answers.
   A question needs to be answered.
   Any question creates an empty space in the mind of the student that needs to be filled by answers.
